### ISSUE TITLE
jenkins 빌드 시 가~끔 빌드 12시간 넘도록 안될 때 있음.

### ISSUE THREAD

**Issue by oeeen** [WoowaCrew/WoowaCrew#317]
Jenkins 빌드 시에 가~끔 메모리 부족 같은 오류 뜨면서 빌드가 안될 때 있음.

원인 파악 안됨.(진짜 메모리 부족인가)

**Comment by oeeen** [comment]
이번에도 발생했으나.....
```
> Task :acceptanceTest
03:50:08.451 [INFO ] [Thread-14] [o.s.s.c.ThreadPoolTaskExecutor] - Shutting down ExecutorService 'applicationTaskExecutor'
03:50:08.463 [INFO ] [Thread-14] [o.s.o.j.LocalContainerEntityManagerFactoryBean] - Closing JPA EntityManagerFactory for persistence unit 'default'
03:50:08.463 [INFO ] [Thread-14] [o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl] - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
03:50:08.474 [INFO ] [Thread-21] [o.s.s.c.ThreadPoolTaskExecutor] - Shutting down ExecutorService 'applicationTaskExecutor'
03:50:08.493 [INFO ] [Thread-21] [o.s.o.j.LocalContainerEntityManagerFactoryBean] - Closing JPA EntityManagerFactory for persistence unit 'default'
03:50:08.494 [INFO ] [Thread-21] [o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl] - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
03:50:08.500 [INFO ] [Thread-25] [o.s.s.c.ThreadPoolTaskExecutor] - Shutting down ExecutorService 'applicationTaskExecutor'
03:50:08.502 [INFO ] [Thread-25] [o.s.o.j.LocalContainerEntityManagerFactoryBean] - Closing JPA EntityManagerFactory for persistence unit 'default'
03:50:08.502 [INFO ] [Thread-25] [o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl] - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
03:50:08.509 [INFO ] [Thread-25] [o.s.b.f.s.DisposableBeanAdapter] - Invocation of destroy method failed on bean with name 'inMemoryDatabaseShutdownExecutor': org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-199]
03:50:08.509 [INFO ] [Thread-25] [com.zaxxer.hikari.HikariDataSource] - HikariPool-4 - Shutdown initiated...
03:50:08.513 [INFO ] [Thread-25] [com.zaxxer.hikari.HikariDataSource] - HikariPool-4 - Shutdown completed.
```

위 상황에서 멈춰있음

**Comment by oeeen** [comment]
```
> Task :acceptanceTest
15:48:20.131 [INFO ] [Thread-14] [o.s.s.c.ThreadPoolTaskExecutor] - Shutting down ExecutorService 'applicationTaskExecutor'
15:48:20.135 [INFO ] [Thread-21] [o.s.s.c.ThreadPoolTaskExecutor] - Shutting down ExecutorService 'applicationTaskExecutor'
15:48:20.137 [INFO ] [Thread-21] [o.s.o.j.LocalContainerEntityManagerFactoryBean] - Closing JPA EntityManagerFactory for persistence unit 'default'
15:48:20.137 [INFO ] [Thread-21] [o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl] - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
15:48:20.139 [INFO ] [Thread-14] [o.s.o.j.LocalContainerEntityManagerFactoryBean] - Closing JPA EntityManagerFactory for persistence unit 'default'
15:48:20.140 [INFO ] [Thread-14] [o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl] - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
15:48:20.147 [INFO ] [Thread-25] [o.s.s.c.ThreadPoolTaskExecutor] - Shutting down ExecutorService 'applicationTaskExecutor'
15:48:20.149 [INFO ] [Thread-25] [o.s.o.j.LocalContainerEntityManagerFactoryBean] - Closing JPA EntityManagerFactory for persistence unit 'default'
15:48:20.150 [INFO ] [Thread-25] [o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl] - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
```

**Comment by oeeen** [comment]
```
woowacrew.article.slack.service.SlackMessageInternalServiceTest > findRecentlyMessage() STANDARD_OUT
    03:35:23.398 [INFO ] [Test worker] [c.u.s.s.i.SlackWebSocketSessionImpl] - connecting to slack
    03:35:23.615 [ERROR] [Test worker] [c.u.s.s.i.SlackWebSocketSessionImpl] - Error during authentication : ratelimited
    03:35:23.615 [ERROR] [Test worker] [w.a.s.s.SlackMessageInternalService] - Create slack message fail : 
    java.net.ConnectException: ratelimited
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:338)
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:292)
        at woowacrew.article.slack.service.SlackMessageInternalService.createSlackMessage(SlackMessageInternalService.java:49)
        at woowacrew.article.slack.service.SlackMessageInternalService.save(SlackMessageInternalService.java:39)
        at woowacrew.article.slack.service.SlackMessageInternalServiceTest.saveSlackMessage(SlackMessageInternalServiceTest.java:56)
        at woowacrew.article.slack.service.SlackMessageInternalServiceTest.findRecentlyMessage(SlackMessageInternalServiceTest.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:92)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)

woowacrew.article.slack.service.SlackMessageInternalServiceTest > findRecentlyMessage() FAILED
    woowacrew.article.slack.exception.CreateSlackMessageFailException: 슬랙 메세지를 저장하는데 실패하였습니다.
        at woowacrew.article.slack.service.SlackMessageInternalService.save(SlackMessageInternalService.java:43)
        at woowacrew.article.slack.service.SlackMessageInternalServiceTest.saveSlackMessage(SlackMessageInternalServiceTest.java:56)
        at woowacrew.article.slack.service.SlackMessageInternalServiceTest.findRecentlyMessage(SlackMessageInternalServiceTest.java:140)
```

에서 아래 부분 참조

```
woowacrew.article.slack.service.SlackMessageInternalServiceTest > findRecentlyMessage() STANDARD_OUT
    03:35:23.398 [INFO ] [Test worker] [c.u.s.s.i.SlackWebSocketSessionImpl] - connecting to slack
    03:35:23.615 [ERROR] [Test worker] [c.u.s.s.i.SlackWebSocketSessionImpl] - Error during authentication : ratelimited
```

**Comment by oeeen** [comment]
```
> Task :acceptanceTest
13:52:28.786 [INFO ] [Thread-15] [o.s.s.c.ThreadPoolTaskExecutor] - Shutting down ExecutorService 'applicationTaskExecutor'
13:52:28.788 [INFO ] [Thread-15] [o.s.o.j.LocalContainerEntityManagerFactoryBean] - Closing JPA EntityManagerFactory for persistence unit 'default'
13:52:28.788 [INFO ] [Thread-15] [o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl] - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
13:52:28.798 [INFO ] [Thread-22] [o.s.s.c.ThreadPoolTaskExecutor] - Shutting down ExecutorService 'applicationTaskExecutor'
13:52:28.800 [INFO ] [Thread-22] [o.s.o.j.LocalContainerEntityManagerFactoryBean] - Closing JPA EntityManagerFactory for persistence unit 'default'
13:52:28.800 [INFO ] [Thread-22] [o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl] - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
13:52:28.826 [INFO ] [Thread-26] [o.s.s.c.ThreadPoolTaskExecutor] - Shutting down ExecutorService 'applicationTaskExecutor'
13:52:28.828 [INFO ] [Thread-26] [o.s.o.j.LocalContainerEntityManagerFactoryBean] - Closing JPA EntityManagerFactory for persistence unit 'default'
13:52:28.828 [INFO ] [Thread-26] [o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl] - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
```

**Comment by oeeen** [comment]
<img width="723" alt="스크린샷 2020-02-16 오후 2 42 17" src="https://user-images.githubusercontent.com/16066456/74599778-ea230180-50ca-11ea-945b-6062b6dc316e.png">
